last_update = 1707308064330
api_url = "https://api.playit.cloud/agent"
ping_target_addresses = []
control_address = "control.playit.gg"
refresh_from_api = true
api_refresh_rate = 5000
ping_interval = 5000
secret_key = "a44992aba561ae2e84de043f87a3b862322ef89e8307bf08ce8fc4c3d3352038"

[[mappings]]
name = "unnamed"
proto = "both"
tunnel_ip = "147.185.221.18"
tunnel_from_port = 24787
local_port = 8888

[[mappings]]
name = "unnamed"
proto = "tcp"
tunnel_ip = "147.185.221.223"
tunnel_from_port = 34931
local_port = 8080

[[mappings]]
name = "terariacraft"
proto = "tcp"
tunnel_ip = "147.185.221.180"
tunnel_from_port = 26366
local_port = 7777
