name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Inject Discord Token into main.py
      run: |
        # Replace REPLACEME in main.py with the Discord token from GitHub Secrets
        sed -i "s/TOKEN = \"REPLACEME\"/TOKEN = \'${{ secrets.DISCORD_TOKEN }}\'/" main.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --noconsole main.py

    - name: Restore original main.py (remove hardcoded token)
      run: |
        git checkout main.py

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/
