- name: PyInstaller Build
  uses: eric2788/pyinstaller-build@0.1.3
  with:
    main: main
    dist: ""  # optional, default is ./dist
    python_version: ""  # optional, default is 3.9.7
    pyinstaller_version: ""  # optional, default is 4.7
    artifact: ""  # optional, default is main
    use-dependencies: true  # optional, default is true
    no-console: ""  # optional, default is false
    icon: ""  # optional, default is NONE
